version: "3"

services:
  db:
      image: postgres:latest
      restart: always
      env_file:
        - .env
      environment:
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_NAME}
      ports:
        - "${DATABASE_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URI: ${DATABASE_URI}
    ports:
      - "8080:8080"
    command: poetry run flask run --host=0.0.0.0 --port=8080

volumes:
  postgres_data:
